version: '3'

services:
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
    ports:
      - '9000:9000'
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'sleeping for 10 seconds while minio starts...';
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb   minio/configs;
      /usr/bin/mc mb   minio/manifest;
      /usr/bin/mc policy set public minio/configs;
      /usr/bin/mc cp --recursive /configs/ minio/configs/ ;
      /usr/bin/mc policy set public minio/manifest;
      /usr/bin/mc cp --recursive /manifest/ minio/manifest/ ;
      exit 0;
      "
    volumes:
      - ./configs:/configs
      - ./manifest:/manifest
  hydro-scalar:
    build: .
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_S3_REGION=ap-northeast-1
      - AWS_S3_BUCKET=media
      - S3_BUCKET=media
      - AWS_S3_ENDPOINT=minio:9000
      - AWS_VIRTUAL_HOSTING=False
      - AWS_S3_DISABLE_SSL=True
      - AWS_S3_FORCE_PATH_STYLE=True
      - AWS_HTTPS=False
    volumes:
      - ./:/workspaces