plugin: hydrograph_scaler

event_config:
  realization:
    id: 1
    seed: 1234
  event:
    id: 1
    seed: 5678
  time_window:
    start_time: 2018-01-01T01:01:01.000000001-05:00
    end_time: 2019-01-01T01:01:01.000000001-05:00

models:
  - model:
      name: hsm
      modelfiles:
        - /data/test-sim/inputs/hsm.json
      inputs: 
      outputs:
        - /data/test-sim/outputs/hsm1.csv
        - /data/test-sim/outputs/hsm2.csv
        - /data/test-sim/outputs/hsm3.csv
