target_plugin: hydrograph_scaler
model_configuration:
  model_name: hsm
  model_configuration_path: /data/hydrographscaler/hsm.json
model_links:
  linked_inputs:
  required_outputs:
  - name: hsm1.csv
    parameter: flow
    format: csv
  - name: hsm2.csv
    parameter: flow
    format: csv
  - name: hsm3.csv
    parameter: flow
    format: csv
event_config:
  output_destination: /data/hydrographscaler/output/
  realization_number: 1
  event_number: 1
  time_window:
    starttime: 2018-01-01T01:01:01.000000001-05:00
    endtime: 2020-12-31T01:01:01.000000001-05:00
  event_seed: 5678
  realization_seed: 1234