target_plugin: hydrograph_scaler
model_configuration:
  model_name: hsm
  model_configuration_paths:
  - /data/hydrographscaler/hsm.json
model_links:
  linked_inputs:
  required_outputs:
  - name: hsm1.csv
    parameter: flow
    format: csv
  - name: hsm2.csv
    parameter: flow
    format: csv
  - name: hsm3.csv
    parameter: flow
    format: csv
event_config:
  output_destination: /data/hydrographscaler/output/
  realization:
    index: 1
    seed: 1234
  event:
    index: 1
    seed: 5678
  time_window:
    starttime: 2018-01-01T01:01:01.000000001-05:00
    endtime: 2020-12-31T01:01:01.000000001-05:00